---
- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ docker_packages }}"

- name: "Launch portainer container"
  docker_container:
    name: portainer
    image: portainer/portainer:latest
    restart_policy: always
    network_mode: host
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
  when: portainer_enable 

- name: "Allow new incoming SYN packets on TCP port 9000 (Portainer)"
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9000"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new HTTP connections.  
  notify: docker_run_iptables_save
  when: portainer_enable  

- name: "Configure docker daemon"
  template: >
    src=daemon.json
    dest=/etc/docker/daemon.json
  notify: restart_docker

- name: "Run Hello Wolrd Docker Container"
  docker_container: 
    name: hello_world
    image: 'hello-world'

- name: "Add active Docker Containers"
  docker_container: 
    "{{ item }}"
  loop: "{{ active_containers }}"

